test pr

diff --git a/.github/workflows/ci-pr.yml b/.github/workflows/ci-pr.yml
--- a/.github/workflows/ci-pr.yml
+++ b/.github/workflows/ci-pr.yml
@@ -21,17 +21,8 @@ jobs:
           cat crda.json  | jq 
           echo CRDA sarif output
           cat crda.sarif  | jq 
-      - name: Upload result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v1
-        with:
-          sarif_file: crda.sarif
-      - name: Save Intermediate files
-        run: |  
-          mkdir -p uploads
-          mv crda.sarif uploads 
-          mv crda.json uploads 
-      - name: Upload merged Results  
-        uses: actions/upload-artifact@v2
-        with: 
-          name: workfiles
-          path: ./uploads
+          set TV=$(cat crda.json | jq .total_direct_vulnerabilities)
+          if [ "$TV" -neq "0" ]; then
+            echo "FAILED";
+            exit $TV;
+          fi
